# Generated by Django 5.2.8 on 2026-01-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='username',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
