# Generated by Django 5.2.8 on 2026-01-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendAPI', '0003_alter_siteuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='username',
        ),
    ]
