# Generated by Django 5.2.8 on 2026-01-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendAPI', '0004_remove_siteuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='username',
            field=models.CharField(default='Anonymous', max_length=150),
        ),
    ]
