# Generated by Django 6.0.2 on 2026-07-12 10:24

import django.core.validators
import django.db.models.deletion
import game.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('genres', models.JSONField(blank=True, default=game.models._default_genres)),
                ('status', models.CharField(choices=[('waiting', 'Waiting for players'), ('playing_round', 'Game Round in progress'), ('playing_break', 'Game Break in progress'), ('finished', 'Game finished'), ('aborted', 'Game aborted')], default='waiting', max_length=20)),
                ('playbackDuration', models.FloatField(blank=True, default=30, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)])),
                ('breakDuration', models.FloatField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)])),
                ('mode', models.CharField(choices=[('normal', 'GAME_MODE_NORMAL'), ('speed', 'GAME_MODE_SPEED')], default='normal', max_length=20)),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('trackCount', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('uid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('visibility', models.CharField(choices=[('public', 'PUBLIC'), ('friends', 'FRIENDS'), ('private', 'PRIVATE')], max_length=20)),
                ('fuzzy', models.BooleanField(default=True)),
                ('reveal', models.BooleanField(default=False)),
                ('current_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in_games', to='music.track')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
