# Generated by Django 5.2.8 on 2026-07-10 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_initial'),
        ('game', '0001_initial'),
        ('music', '0001_initial'),
        ('stats', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='owned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_games', to='userprofile.profile'),
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='games_played', through='stats.UserGameStats', to='userprofile.profile'),
        ),
        migrations.AddField(
            model_name='game',
            name='playlist',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game', to='music.playlist'),
        ),
        migrations.AddField(
            model_name='game',
            name='room',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.room'),
        ),
    ]
