# Generated by Django 5.2.8 on 2026-07-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('normal', 'GAME_MODE_NORMAL'), ('speed', 'GAME_MODE_SPEED')], default='normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='playlist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='music.playlist'),
        ),
    ]
