# Generated by Django 5.2.8 on 2026-03-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='username',
        ),
    ]
