# Generated by Django 6.0.2 on 2026-06-29 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRoundStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.FloatField(default=30)),
                ('artist_found', models.BooleanField(default=False)),
                ('title_found', models.BooleanField(default=False)),
                ('artist_found_at', models.FloatField(default=-1)),
                ('title_found_at', models.FloatField(default=-1)),
                ('xp_earned', models.PositiveIntegerField(default=0)),
                ('ranking', models.PositiveIntegerField(default=1)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameRoundStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.game')),
                ('track', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.track')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='UserGameStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_won', models.BooleanField(default=False)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='game.game')),
            ],
            options={
                'ordering': ['-played_at'],
            },
        ),
    ]
