# Generated by Django 6.0.2 on 2026-07-12 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamestats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_played', to='userprofile.profile'),
        ),
        migrations.AddField(
            model_name='userroundstats',
            name='game_stats',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='round_stats', to='stats.usergamestats'),
        ),
        migrations.AddField(
            model_name='userroundstats',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile'),
        ),
        migrations.AddField(
            model_name='userroundstats',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.gameroundstats'),
        ),
        migrations.AddField(
            model_name='gameroundstats',
            name='players',
            field=models.ManyToManyField(related_name='played_rounds', through='stats.UserRoundStats', to='userprofile.profile'),
        ),
        migrations.AlterUniqueTogether(
            name='usergamestats',
            unique_together={('game', 'player')},
        ),
    ]
