# Generated by Django 5.2.8 on 2026-03-10 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroundstat',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userprofile.profile'),
        ),
        migrations.AddField(
            model_name='gamestat',
            name='players',
            field=models.ManyToManyField(related_name='games_played', to='userprofile.profile'),
        ),
        migrations.AddField(
            model_name='gameroundstat',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='stats.gamestat'),
        ),
        migrations.AddField(
            model_name='userroundstat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.profile'),
        ),
        migrations.AddField(
            model_name='userroundstat',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='stats.gameroundstat'),
        ),
    ]
