# Generated by Django 5.2.8 on 2026-07-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergamestats',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
