openapi: 3.0.3
info:
  title: ft_transcendence API
  version: 0.1.0
  description: Internal API for the webapp.
  contact:
    name: ft_transcendence Team
    email: support@example.com
servers:
  - url: http://localhost:8000

paths:
  /api/auth/register:
    $ref: ./paths/auth.yaml#/register
  /api/auth/login:
    $ref: ./paths/auth.yaml#/login
  /api/auth/refresh:
    $ref: ./paths/auth.yaml#/refresh
  /api/auth/logout:
    $ref: ./paths/auth.yaml#/logout
  /api/auth/password:
    $ref: ./paths/auth.yaml#/password
  /api/auth/delete:
    $ref: ./paths/auth.yaml#/delete
  /api/social/friends:
    $ref: ./paths/social.yaml#/friends-list
  /api/social/friends-search:
    $ref: ./paths/social.yaml#/friends-search
  /api/social/friends-request:
    $ref: ./paths/social.yaml#/friends-requests
  /api/social/friends-request/send:
    $ref: ./paths/social.yaml#/friends-requests-send
  /api/social/friends-request/respond:
    $ref: ./paths/social.yaml#/friends-requests-respond
  /api/social/friend/remove:
    $ref: ./paths/social.yaml#/friend-remove
  /api/social/message:
    $ref: ./paths/social.yaml#/social-message
  /api/social/notifs:
    $ref: ./paths/social.yaml#/notif
  /api/social/notifs_read":
    $ref: ./paths/social.yaml#/notif-read
  /api/profile:
    $ref: ./paths/profile.yaml#/profile
  /api/profile/search:
    $ref: ./paths/profile.yaml#/search
  /api/profile/guest-create:
    $ref: ./paths/profile.yaml#/guest-create
  /api/profile/guest-delete:
    $ref: ./paths/profile.yaml#/guest-delete
  /api/stats/global:
    $ref: ./paths/stats.yaml#/global
  /api/stats/leaderboard:
    $ref: ./paths/stats.yaml#/leaderboard
  /api/stats/history:
    $ref: ./paths/stats.yaml#/history
  /api/game/{ROOMID}:
    $ref: ./paths/game.yaml#/game-common
  WS/#friend-chat:
    $ref: ./paths/websocket.yaml#/WS-friend-chat
  WS/#notif:
    $ref: ./paths/websocket.yaml#/WS-notif
  WS/#friend-request:
    $ref: ./paths/websocket.yaml#/WS-friend-request
  WS/#game:
    $ref: ./paths/websocket.yaml#/WS-game

components:
  schemas:
    Profile:
      $ref: ./components/schemas.yaml#/Profile
    OwnProfile:
      $ref: ./components/schemas.yaml#/OwnProfile
    LightProfile:
      $ref: ./components/schemas.yaml#/LightProfile
    ValidationError:
      $ref: ./components/schemas.yaml#/ValidationError
    AuthError:
      $ref: ./components/schemas.yaml#/AuthError
    ConflictError:
      $ref: ./components/schemas.yaml#/ConflictError
    TokenResponse:
      $ref: ./components/schemas.yaml#/TokenResponse
    PasswordChangeResponse:
      $ref: ./components/schemas.yaml#/PasswordChangeResponse
    DescriptionResponse:
      $ref: ./components/schemas.yaml#/DescriptionResponse
    SerializerErrorResponse:
      $ref: ./components/schemas.yaml#/SerializerErrorResponse
    ProfileDeleteRequest:
      $ref: ./components/schemas.yaml#/ProfileDeleteRequest
    ProfilePasswordChangeRequest:
      $ref: ./components/schemas.yaml#/ProfilePasswordChangeRequest
    GlobalStatsResponse:
      $ref: ./components/schemas.yaml#/GlobalStatsResponse
    LeaderboardResponse:
      $ref: ./components/schemas.yaml#/LeaderboardResponse
    HistoryResponse:
      $ref: ./components/schemas.yaml#/HistoryResponse
    ExtUserInfo:
      $ref: ./components/schemas_users.yaml#/ExtUserInfo
    FriendInfo:
      $ref: ./components/schemas_social.yaml#/FriendInfo
    Message:
      $ref: ./components/schemas_social.yaml#/Message
    Notif - Requests: 
      $ref: ./components/schemas_social.yaml#/NotifRequests
    Notif - Accepted:
      $ref: ./components/schemas_social.yaml#/NotifAccepted
    Game - GameData:
      $ref: ./components/schemas_game.yaml#/GameData
    Game - GamePlayer:
      $ref: ./components/schemas_game.yaml#/GamePlayer
    WS - StoC - friend-chat:
      $ref: ./components/schemas_ws.yaml#/WS-StoC-FriendChat
    WS - StoC - notif:
      $ref: ./components/schemas_ws.yaml#/WS-StoC-Notif
    WS - StoC - friend-request:
      $ref: ./components/schemas_ws.yaml#/WS-StoC-FriendRequests
    WS - StoC - game:
      $ref: ./components/schemas_ws.yaml#/WS-StoC-Game
    WS - CtoS - friend-chat:
      $ref: ./components/schemas_ws.yaml#/WS-CtoS-FriendChat
    WS - CtoS - game:
      $ref: ./components/schemas_ws.yaml#/WS-CtoS-Game
    
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

tags:
  - name: auth
    description: Authentication and registration endpoints.
  - name: social
    description: Friend list and friend request endpoints.
  - name: profile
    description: User profile and account management endpoints.
  - name: stats
    description: User statistics
  - name: game
    description: "All game related endpoints"
  - name: websockets
    description: "Websockets data (Open AI don't handle websocket -> Posts = MODULES, Requests = Client to Server, Reponse = Server to Clients)"
