openapi: 3.0.3
info:
  title: ft_transcendence API
  version: 0.1.0
  description: Internal API for the webapp.
  contact:
    name: ft_transcendence Team
    email: support@example.com
servers:
  - url: http://localhost:8000

paths:
  /api/auth/register:
    $ref: ./paths/auth.yaml#/register
  /api/auth/login:
    $ref: ./paths/auth.yaml#/login
  /api/auth/refresh:
    $ref: ./paths/auth.yaml#/refresh
  /api/auth/logout:
    $ref: ./paths/auth.yaml#/logout
  /api/auth/friends:
    $ref: ./paths/auth.yaml#/friends
  /api/auth/friend-request:
    $ref: ./paths/auth.yaml#/friend-request
  /api/auth/friend-request/send:
    $ref: ./paths/auth.yaml#/friend-request-send
  /api/auth/friend-request/respond:
    $ref: ./paths/auth.yaml#/friend-request-respond
  /api/profile:
    $ref: ./paths/profile.yaml#/profile
  /api/profile/search:
    $ref: ./paths/profile.yaml#/search
  /api/profile/guest-create:
    $ref: ./paths/profile.yaml#/guest-create
  /api/profile/guest-delete:
    $ref: ./paths/profile.yaml#/guest-delete
  /api/users/me:
    $ref: ./paths/users.yaml#/me
  /api/users/{username}:
    $ref: ./paths/users.yaml#/byUsername
  /api/users/me/password:
    $ref: ./paths/users.yaml#/password
  /api/users/me/avatar:
    $ref: ./paths/users.yaml#/avatar

components:
  schemas:
    User:
      $ref: ./components/schemas.yaml#/User
    Profile:
      $ref: ./components/schemas.yaml#/Profile
    LightProfile:
      $ref: ./components/schemas.yaml#/LightProfile
    Friendship:
      $ref: ./components/schemas.yaml#/Friendship
    ValidationError:
      $ref: ./components/schemas.yaml#/ValidationError
    AuthError:
      $ref: ./components/schemas.yaml#/AuthError
    ConflictError:
      $ref: ./components/schemas.yaml#/ConflictError
    TokenResponse:
      $ref: ./components/schemas.yaml#/TokenResponse
    WS Reponse:
      $ref: ./components/schemas_ws.yaml#/WSReponse
    WS Requests:
      $ref: ./components/schemas_ws.yaml#/WSRequest
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

tags:
  - name: auth
    description: Authentication and registration endpoints.
  - name: profile
    description: User profile endpoints.
  - name: users
    description: User profile and account management.
