# Generated by Django 5.2.8 on 2026-01-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_username_alter_siteuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='Anonymous', max_length=150),
        ),
    ]
