# Generated by Django 5.2.8 on 2026-01-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='username',
            field=models.CharField(default='Anonymous', max_length=20, unique=True),
        ),
    ]
