# Generated by Django 5.2.8 on 2026-02-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_siteuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='username',
            field=models.CharField(default='Anonymous', max_length=20, unique=True),
        ),
    ]
