# Generated by Django 6.0.3 on 2026-03-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
