# Generated by Django 5.2.8 on 2026-03-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
    ]
