# Generated by Django 6.0.3 on 2026-03-12 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_profile_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_of', to=settings.AUTH_USER_MODEL),
        ),
    ]
