# Generated by Django 6.0.3 on 2026-03-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='direct_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_direct',
            field=models.BooleanField(default=False),
        ),
    ]
