services:
  backend:
    container_name: backend
    image: transcendence-backend
    build: ./backend/build/
    volumes:
      - ./backend/:/backend/
    ports:
      - "8000:8000"
    env_file: ./backend/.env
    environment:
      - APP_MODE=${MODE:-run}
      - PYTHONUNBUFFERED=1

  nginx:
    container_name: nginx
    image: transcendence-nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./backend/DB/static:/backend-media:ro
    depends_on:
      - backend
