server {
	listen 80;
	server_name _;

	root /usr/share/nginx/html;
	index index.html;

	location /DB/static/ {
		alias /backend-media/;
	}

	location /static/ {
		alias /backend-static/;
	}

	location /media/ {
		alias /backend-media/;
	}

	location / {
		try_files $uri $uri/ /index.html;
	}

	location /api {
		proxy_pass http://backend:8000;
	}
}
