# Generated by Django 6.0.2 on 2026-04-11 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(default='', max_length=100, unique=True)),
                ('rss_url', models.URLField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('itunes_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('kind', models.CharField(blank=True, max_length=100, null=True)),
                ('preview_url', models.URLField(blank=True, max_length=500, null=True)),
                ('artwork_url', models.URLField(blank=True, max_length=500, null=True)),
                ('playlists', models.ManyToManyField(related_name='tracks', to='music.playlist')),
            ],
        ),
    ]
