# Generated by Django 5.2.8 on 2026-07-10 14:06

import django.db.models.deletion
import userprofile.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Anonymous', max_length=20, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=userprofile.models.avatar_path)),
                ('exp_points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('guest', models.BooleanField(default=True)),
                ('is_online', models.BooleanField(default=True)),
                ('active_ws_connections', models.PositiveIntegerField(default=0)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('username', 'Anonymous'), _negated=True), fields=('username',), name='unique_username_unless_anonymous')],
            },
        ),
    ]
