# Generated by Django 5.2.8 on 2026-03-02 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('username', models.CharField(default='Anonymous', max_length=20, unique=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('exp_points', models.IntegerField(default=0)),
                ('badges', models.CharField(default='Deaf Octopus', max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
