# Generated by Django 5.2.8 on 2026-03-05 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_guest',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='badges',
            field=models.CharField(choices=[('Deaf Octopus', 'Deaf Octopus'), ('Dazed Jellyfish', 'Dazed Jellyfish'), ('Distracted Pigeon', 'Distracted Pigeon'), ('Curious Cat', 'Curious Cat'), ('Attentive Owl', 'Attentive Owl'), ('Rhythmic Raptor', 'Rhythmic Raptor'), ('Sonic Shark', 'Sonic Shark'), ('Echolocating Bat', 'Echolocating Bat')], default='Deaf Octopus', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_pp.jpg', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
