# Generated by Django 5.2.8 on 2026-03-17 17:48

import userprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_alter_profile_image_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default_pp.jpg', upload_to=userprofile.models.profile_pic_path),
        ),
    ]
